apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: managedclusteraddons.addon.open-cluster-management.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Progressing")].status
    name: Progressing
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].status
    name: Available
    type: string
  group: addon.open-cluster-management.io
  names:
    kind: ManagedClusterAddOn
    listKind: ManagedClusterAddOnList
    plural: managedclusteraddons
    singular: managedclusteraddon
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ManagedClusterAddOn is the Custom Resource object which holds the
        current state of an add-on. This object is used by add-on operators to convey
        their state. The resource should be created in the ManagedCluster namespace.
      type: object
      required:
      - spec
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: spec holds configuration that could apply to any operator.
          type: object
        status:
          description: status holds the information about the state of an operator.  It
            is consistent with status information across the Kubernetes ecosystem.
          type: object
          properties:
            conditions:
              description: conditions describe the state of the managed and monitored
                components for the operator.
              type: array
              items:
                description: AddOnStatusCondition represents the state of the add-on
                  managed and monitored components.
                type: object
                required:
                - lastTransitionTime
                - status
                - type
                properties:
                  lastTransitionTime:
                    description: lastTransitionTime is the time of the last update
                      to the current status property.
                    type: string
                    format: date-time
                  message:
                    description: message provides additional information about the
                      current condition. This is only to be consumed by humans.
                    type: string
                  reason:
                    description: reason is the CamelCase reason for the condition's
                      current status.
                    type: string
                  status:
                    description: status of the condition. Status can be True, False,
                      Unknown.
                    type: string
                  type:
                    description: type specifies the aspect reported by this condition.
                    type: string
            description:
              description: description represents the detailed description of the
                add-on.
              type: string
            displayName:
              description: displayName represents the name of add-on that will be
                displayed.
              type: string
            relatedObjects:
              description: 'relatedObjects is a list of objects that are "interesting"
                or related to this operator. Common uses are: 1. the detailed resource
                driving the operator 2. operator namespaces 3. operand namespaces
                4. related ClusterManagementAddon resource'
              type: array
              items:
                description: ObjectReference contains enough information to let you
                  inspect or modify the referred object.
                type: object
                required:
                - group
                - name
                - resource
                properties:
                  group:
                    description: group of the referent.
                    type: string
                  name:
                    description: name of the referent.
                    type: string
                  resource:
                    description: resource of the referent.
                    type: string
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
